<?
//Compilation
$mess_code = "Enter code";
$mess_titre = "Untitled";
$mess_msg_erreur = "You must enter FAUST code";
$mess_ret_public = "Your insertion in public codes submission has been registered";
$mess_ret_public_err = "Code contains errors, to publish it you have to correct it and compile it again";
$mess_sav = "Code saved";
$mess_sav_err = "Code contains errors,to save it you have to correct it and compile it again. ";
$mess_compil_success = "Compilation successfull";
$mess_compil_failure = "Error during the compilation. The errors are :";
$mess_telecharger = "Download";
?>